---
title: "Trading_Com_Dados_R"
output: html_document
---

Excelente material disponibilizado pela Trading com dados.
Segue o link da playlist:
https://youtube.com/playlist?list=PLjdDBZW3EmXcIuLGbS3vp53H-DqMZ4IOS


```{r}

#Dados de negociação com 1 dia de atraso.
install.packages('BatchGetSymbols')
#Possível fazer análise técnica no R.
install.packages('quantmod')
#Dados fundamentalistas das ações brasileiras
install.packages('GetDFPData')
```

```{r}
library(BatchGetSymbols)
library(quantmod)
library(GetDFPData)
#Gráficos
library(ggplot2)
#Estética
library(ggthemes)
#Mudar formato de algumas tabelas
library(reshape2)
#Para outras aplicações
library(plyr)

```

```{r}
#Início do código
# Seção 01
?BatchGetSymbols

acao = "WEGE3.SA" #sempre precisa incluir o "SA".
#Data Inicial
di = "2016-01-01"
#Data Final
df = Sys.Date()
#BOVESPA como Benchmark
benchmark = '^BVSP'

dados_acao = BatchGetSymbols(
  tickers = acao,
  first.date = di,
  last.date = df,
  bench.ticker = benchmark,
)

#Não vou precisar de todos os dados, somente df.tickers
dados_acao = dados_acao$df.tickers

View(dados_acao)

p = ggplot(dados_acao, aes(ref.date, price.adjusted)) + geom_line(color = 'blue')
p

p + labs(x = 'Data', y = 'Preço Ajustado', title = "Variação do preço da ação", subtitle = "01/2016 até hoje")
```

```{r}
#Seção 2
#Dados de várias ações de uma vez

ibov = GetIbovStocks()
View(ibov)

ibov$tickersSA = paste(ibov$tickers, ".SA", sep="")

#Pegar os dados de todas as ações que compoem o IBOV:

dados_ibov = BatchGetSymbols(
  tickers = ibov$tickersSA,
  first.date = di,
  last.date = df,
  bench.ticker = benchmark,
)

View(dados_ibov)
#Trouxe em formato de lista. Mudar para dataframe e utilizar somente a segunda parte da lista que tem os dados que nos interessa.

dados_ibov = dados_ibov$df.tickers
View(dados_ibov)
```

```{r}

#Manipular a tabela para selecionar uma ação por vez

dados_ibov2 = dlply(dados_ibov, .(ticker), function(x) {rownames(x)=x$row; x$row = NULL;x})

#.ticker indica que vai separar esse df (dados_ibov) em vários utros DF de acordo com a coluna "ticker"
#function(x) : uma função para separar as linhas de acordo com o ativo de referência, vai dar uma lista de DFs.

View(dados_ibov2)

#Tinham 82 ações no ibov mas ele só retornou 75 DFs, isso pq nem todas as ações tem todos os dados no período que selecionamos 
#(01/01/2016 até hoje)

# Para selecionar uma ação específica. Por exemplo, AZUL4. Segunda linha do data frame dados_ibov2:

azul4 = dados_ibov2[[2]]
View(azul4)

```

```{r}
#Melhor forma de manipular esses datos é colocar em um formato onde os preços de ajuste das ações estejam separadas por coluna, cada 
#coluna corresponde aos preços de fechamento da ação, e cada linha corresponde a um pregão.'

# Para a ação ZUL4, selecionar somente as coluna 6 (Preço ajustado) e 7 (Data)
azul4 = dados_ibov2[[2]][c(7,6)] #mudando a ordem para a coluna data vir primeiro.
View(azul4)

#Mudar os nomes das colunas: ref.date passará a se chamar "Data" e price.adjusted passará a se chamar "Preços" com o ticker da ação.
colnames(azul4) = c("Data", paste("Preços", dados_ibov2[[2]][1,8]))

#Criar um looping (for) para fazer os dois comandos anteriores para todas as ações de dados_ibov2:

acao = dados_ibov2[[1]][c(7,6)]
colnames(acao) = c("Data", paste("Preços", dados_ibov2[[1]][1,8]))

for(i in 2:75){
  novaacao = dados_ibov2[[i]][c(7,6)]
  colnames(novaacao) = c("Data", paste("Preços", dados_ibov2[[i]][1,8]))
  acao = merge(acao, novaacao, by = "Data") #fazendo um "join" entre acao, novaacao e usando a coluna Data como referência)
}
View(acao)
```


Gerando gráficos com várias ações
Ações do setor bancário:

```{r}
f = ggplot()+
  geom_line(data=acao, aes(x = Data, y=acao$'Preços BBAS3.SA', color="Banco do Brasil" ))+
  geom_line(data=acao, aes(x = Data, y=acao$'Preços BBDC4.SA', color="Bradesco" ))+
  geom_line(data=acao, aes(x = Data, y=acao$'Preços ITUB4.SA', color="Itaú Unibanco" ))+
  geom_line(data=acao, aes(x = Data, y=acao$'Preços BBAS3.SA', color="Banco do Brasil" ))+
  geom_line(data=acao, aes(x = Data, y=acao$'Preços SANB11.SA', color="Santander" ))+
  xlab("Data")+
  ylab("Preço")

f$labels$colour = "Bancos"

print(f)
```

Seção 3:
Normalizar preço das ações.

```{r}
#Utilizar índices de referência do mercado financeiro

IBOV = BatchGetSymbols(
  tickers = '^BVSP',
  first.date = di,
  last.date = df,
  bench.ticker = benchmark,
)

IBOV = IBOV$df.tickers

View(IBOV)

SP500 = BatchGetSymbols(
  tickers = '^GSPC',
  first.date = di,
  last.date = df,
  bench.ticker = '^GSPC',
)

SP500 = SP500$df.tickers

View(SP500)

```


```{r}
#Mudando o nome das colunas do IBOV para ficar no mesmo formato das ações:
colnames(IBOV)[6] = 'IBOV'
colnames(IBOV)[7] = 'Data'

#Mudando o nome das colunas do SP500 para ficar no mesmo formato das ações:
colnames(SP500)[6] = 'SP500'
colnames(SP500)[7] = 'Data'

#Selecionando somente as colunas com referentes a Data e valor ajustado dos índices:

IBOV = IBOV[,c(7,6)]
SP500 = SP500[,c(7,6)]

```


```{r}
#Joint de SP500 e IBOV
ibov_sp500=merge(IBOV, SP500, by = 'Data')
View(ibov_sp500)

#Joint de ibov_sp500 e IBOV
total = merge(ibov_sp500, acao, by = 'Data')
View(total)

```


```{r}
#Primeiramente vamos deixar a coluna Data de fora
normalizado = total[,-c(1)]
View(normalizado)

#A idéia da normalização é que todos iniciem do mesmo lugar, no caso o valor 1, para isso vamos pegar o primeiro valor da coluna de
#cada ação e dividir por todos os outros valores da coluna.
# Para a normalização vamos usar a função lapply que tem uma função que já vai aplicar a função de normalização em todas as colunas.
novo_total = data.frame(lapply(normalizado, function(x) x/x[1]))
View(novo_total)

#Retornar a coluna Data. Usando a coluna Data do dataframe 'total'.

novo_total$Data = total$Data

#Plotar o gráfico:

g = ggplot()+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$'Preços.BBAS3.SA', color="Banco do Brasil" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$'Preços.BBDC4.SA', color="Bradesco" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$'Preços.ITUB4.SA', color="Itaú Unibanco" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$'Preços.BBAS3.SA', color="Banco do Brasil" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$'Preços.SANB11.SA', color="Santander" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$IBOV, color="IBOV" ))+
  geom_line(data=novo_total, aes(x = Data, y=novo_total$SP500, color="SP&500" ))+
  xlab("Data")+
  ylab("Preço")

g$labels$colour = "Bancos"

print(g)


```


```{r}
